### ISSUE TITLE
About get5_server_id

### ISSUE THREAD

**Issue by keeradfun** [splewis/get5-web#66]
Not exactly an issue. Need suggestions.
1)If I want to run multiple servers using the same csgo folder and connect it to web panel. Will there be any issue?
2) "get5_server_id" what is the functionality of this cvar if i want to run multiple servers using the same folder.
3) If I change the value of the get5_server_id value in server.cfg will it affect?

**Comment by Technoblazed** [comment]
1) if you start 2 matches at the same time, the remote.json will conflict and may cause match load failures.

**Comment by keeradfun** [comment]
ok ok thank you 👍

**Comment by splewis** [comment]
The purpose of that cvar is so that number can be used to make unique files for temporary paths - i.e. the match config downloaded from the web server. There is no remote.json anymore either - it's remoteN.json (where N is the server id cvar).

Of course, it may be hard to set the cvar if all the servers share the same filesystem. It is only really necessary if you're running tons of things on the same server and you are starting 2 matches at nearly the exact same time (like <1 second apart).

**Comment by keeradfun** [comment]
If i remove the command get5_server_id in get5.cfg and use it in server.cfg. Will it work?

**Comment by splewis** [comment]
Probably not. The plugin hasn't loaded yet when server.cfg is executed.

**Comment by TandelK** [comment]
I think port number are different for both the folders and as well as server.cfg are different for both the servers. If you add both the servers IP , Port and RCON password , i think there are no issues at all because you assign server to accordingly via Panel. I have been running Multiple server from same folder and i did not had any issues with it.

**Comment by splewis** [comment]
I think this is resolved - closing.
