### ISSUE TITLE
steamid.py error

### ISSUE THREAD

**Issue by AzuuraD** [splewis/get5-web#9]
when trying to initialize the main.py file i get an error with the steamid.py file. "no module named valve.steam.id"
![](http://i.imgur.com/0lFcVME.png)

is this just me being stupid? any fix?

**Comment by splewis** [comment]
Did you install the dependecies in the requirements.txt file (see https://github.com/splewis/get5-web#installation)? I'd strongly recommend using a virtualenv like those instructions say.

On a different note, cloning into a ``/var/www/html`` directory probably isn't a good idea, since there's a good chance you end up leaking sensitive information.

**Comment by AzuuraD** [comment]
yeah all those dependencies are installed. i checked just after posting this and was missing python-valve

however now i have a different issue. i've run the manager.py db upgrade and have now run the wsgi script with twisted web. i go to the IP and it redirects me to /matches however it just gives me a message stating "nothing is at this URL"

Is this an issue because i'm not running apache?

**Comment by splewis** [comment]
I don't know. I can't really give any advice on configuring this to work outside of apache.

**Comment by AzuuraD** [comment]
Alright, i switched back to apache2 and took a look at the error logs

https://paste.pound-python.org/show/rKWb89Bnz6DgvxAgsVXe/ this is the error i'm getting, using the same wsgi file as you have in the installation instructions
